### ISSUE TITLE
Racer is slowing down Atom

### ISSUE THREAD

**Issue by whmountains** [Xaeroxe/atom-racer#1]
First of all, thank you @Xaeroxe for forking this repo and continuing to maintain it.  Racer is really a critical tool to use with Rust.

My problem is that when I try to edit a file on a fairly large project, Atom starts lagging.  I can confirm that it's related to Racer because I don't notice any lag when I disable `atom-racer-plus`.  Is there any way to make the atom<->racer communication more performant.  For example, could you interface directly with racer and skip the tmp file?

Thanks in advance!

**Comment by Xaeroxe** [comment]
@whmountains Racer-plus shouldn't be using temporary files.  The atom plugin currently reads from the Stdout of the program and parses it into suggestions, so sadly I don't have any way to boost the performance of that.  However I could look into doing that processing asynchronously and adding suggestions as they become available in order to avoid slowing down your editor.

**Comment by Xaeroxe** [comment]
That asynchronous processing is already being done unfortunately.  So I really don't have any way to improve the performance of this package.  I'm sorry.  I'll leave this issue open so others can read this and maybe someone will think of something I didn't.

**Comment by whmountains** [comment]
Oh yes, I see you eliminated the tmp files by merging a recent PR.  Thanks!

I've been looking over the `atom-racer-plus` and `racer` source code and it seems that the main performance bottleneck is that racer has to warm up it's cache on every completion.  Whatever the cause, the `child_process.spawn()` function is taking 100ms per completion. 

Racer has a daemon mode, maybe we could run it in that mode as a persistent process.  I'm looking into this right now and will report back.

**Comment by Xaeroxe** [comment]
Good idea, thanks!

**Comment by whmountains** [comment]
PR submitted!

It's working fine for me, but I'd feel more comfortable if you would review it yourself before merging.

**Comment by Xaeroxe** [comment]
@whmountains PR merged and version 2 published, thanks!
